### ISSUE TITLE
Update Zcash address encoding / decoding

### ISSUE THREAD

**Issue by hewigovens** [trustwallet/ens-coincodec#13]
Same as Bitcoin lockscript

**Comment by catenocrypt** [comment]
ZCash support is already present.  Pls check and close accordingly.

https://github.com/trustwallet/ens-coincodec/blob/master/zcash.go
https://github.com/trustwallet/ens-coincodec/blob/master/zcash_test.go

**Comment by hewigovens** [comment]
Zcash is just base58 encode/decode, I think we should follow bitcoin lock script
