### ISSUE TITLE
Re-organize package structure

### ISSUE THREAD

**Issue by hewigovens** [trustwallet/ens-coincodec#7]
move coins to specific folder, something like: 
```
├── codec.go
├── codec_test.go
├── coins
│   ├── bitcoin
│   │   ├── bitcoin.go
```

**Comment by catenocrypt** [comment]
My proposal is 3 simple folders:
- coins:  coin implementation files
- common: common, not-coin-specific implementation
- tests: test files, coins and common

**Comment by EnoRage** [comment]
I recommend to read this guide firstly. Especially https://github.com/uber-go/guide/blob/master/style.md#package-names
